SKARA-2397
openjdk/skara pull request #1694
Opened 2024-10-23 21:48 UTC by zhaosongzs

Currently, the Skara bot doesn't recognize "Delivered" as a valid resolution for resolved issues. As a result, when the bot finds an issue in a Resolved or Closed state with "Delivered" resolution, it will change the resolution to "Fixed." However, it shouldn't.

This patch is trying to make the bot recognize "Delivered" as a valid resolution for resolved issues, preventing unnecessary changes.

2024-10-23 23:17 UTC, erikj79 approved these changes

2024-10-24 18:08 UTC, erikj79 requested changes
Hold off on integrating, I think I found another issue.

2024-10-24 18:16 UTC, erikj79 commented
I think we need to check for altfixversion independent of if requestedFixVersion has a value or not. That would make this even more robust.

2024-10-28 22:59 UTC, erikj79 approved these changes

2024-10-29 16:28 UTC, zhaosongzs commented
Thank you for the review!
/integrate

2024-10-29 16:28 UTC, closed without merging