Add /check command to manually execute jcheck
openjdk/skara pull request #954
Opened 2020-11-17 05:46 UTC by amCap1712

2020-11-17 16:11 UTC, edvbld commented
Hi @amCap1712, thanks for working on this!

Please consider adding a unit test for the `/check` command, see e.g. [SummaryTests.java](https://github.com/openjdk/skara/blob/master/bots/pr/src/test/java/org/openjdk/skara/bots/pr/SummaryTests.java) for an example of a unit test for a pull request command.

Thanks,
Erik

2020-11-20 12:28 UTC, amCap1712 commented
Hi @edvbld,
Thanks for the review. I have added a unit test as you asked. Let me know if any other changes are required.
Regards,
Kartik.

2020-11-23 10:37 UTC, rwestberg requested changes

2020-11-23 10:37 UTC, rwestberg commented on bots/pr/src/main/java/org/openjdk/skara/bots/pr/CheckCommand.java
> +            var workItem = new CheckWorkItem(bot, pr, e -> {});
Don't think you actually have to do the check here, `CommandWorkItem` will schedule an additional check after every command anyway. But to force the check to run you'll need to ensure that the "metadata" of the existing check becomes invalid. If you update `metadataComments` to add a special reply marker from the `/check` command, and ensure that the check command outputs it, I think thinks should work.

2020-11-23 10:37 UTC, rwestberg commented on bots/pr/src/test/java/org/openjdk/skara/bots/pr/CheckCommandTests.java
> +            pr.addComment("/check");
Looks like a good start, but it's possible that this test is a bit too simple. Would it still pass if you removed this line (as checking will occur anyway)?

2020-11-23 10:58 UTC, rwestberg commented
> I wanted to test this locally by setting up the skara bots on my own repository but was unable to figure out how to do so due to lack of documentation.

Yeah, sorry about that, it has not really been a priority as no-one else actually run them in "production". It can be a bit complicated to configure them properly for running stand-alone, but if you want to run a test against GitHub instead of the mock implementation that's a bit easier. If you want to try that I'll be happy to assist with the required configuration.

2020-11-24 15:55 UTC, amCap1712 commented
@rwestberg Yes, please. I plan to keep contributing in the future and having such a setup will help me to explore and understand the code much more quickly and in a better way. Hence, I think setting it up will be worth it. Thanks again for the help.

2020-11-24 16:08 UTC, rwestberg commented
Sure, let's start with the required setup for running tests against GitHub (or GitLab) then! You can pass `-Pcredentials=/path/to/credentials.json` where the file contains something like this:

```json
{
    "type": "github",
    "host": "https://github.com",
    "project": "rwestberg/skara-integration",
    "namespace": "github.com",
    "apps": [
        {
            "key": "certificates/sbot.private-key.pkcs8.pem",
            "id": "12837",
            "installation": "195957"
        },
        {
            "key": "certificates/sbot2.private-key.pkcs8.pem",
            "id": "18848",
            "installation": "379295"
        },
        {
            "key": "certificates/sbot3.private-key.pkcs8.pem",
            "id": "19394",
            "installation": "397926"
        }
    ]
}
```

Most tests require two or three different accounts in order to simulate various interactions, so that's why there are a list of them. Each account credential corresponds to a GitHub app that you can create on your account. The `id` can be seen after creating the app, the `installation` value can be found after the app is installed on your account. Finally, the key is the private key you associate with the GitHub app. The path is relative to the .json file. Note that it has to be in PEM format, you'll have to convert the file you get from GitHub.

2020-11-25 12:26 UTC, amCap1712 commented
I have created the 3 Github Apps and generated the .json file as you instructed. How should I proceed ?

2020-11-25 13:06 UTC, rwestberg commented
Now you can use the credentials file when running the tests through Gradle, probably something like this (I usually run from IntelliJ):

`sh gradlew --tests *testCheckRun* -Pcredentials=/path/to/credentials.json`

2021-01-06 13:11 UTC, closed without merging